version: '3.9'

services:
  database:
    image: 'postgres:latest'
    hostname: postgres
    container_name: twitch_backend_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB:  ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - twitch-backend-db:/var/lib/postgresql/data

volumes:
  twitch-backend-db:
    name: twitchbot_db
